version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: order-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: orderhub
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - order-net

  app:
    build: .
    container_name: order-hub-api
    ports:
      - "8080:8080"
    environment:
      APP_DB_URL: jdbc:mysql://db:3306/orderhub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    depends_on:
      - db
    networks:
      - order-net

volumes:
  db-data:

networks:
  order-net:
