services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: local-jenkins
    user: root
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace/order-hub-api   # ğŸ‘ˆ í”„ë¡œì íŠ¸ ë£¨íŠ¸ í†µì§¸ë¡œ ë§ˆìš´íŠ¸
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true

volumes:
  jenkins_home:
